server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge_fase3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Senharoot@123
    hikari:
      read-only: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: America/Sao_Paulo
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    baseline-on-migrate: false   # como o banco está vazio, não precisa baseline
    locations: classpath:db/migration
    validate-on-migrate: false
    clean-disabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: consultas.exchange
  queue: notificacoes.queue
  routingkey: consulta.criada

security:
  jwt:
    secret: ${JWT_SECRET:AAABBBBBBBBBBBBBBBBBBCCDDASS}
    expiration: ${JWT_EXPIRATION:3600000}
