server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge_fase3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    ost: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: consultas.exchange
  queue: notificacoes.queue
  routingkey: consulta.criada

security:
  jwt:
    secret: ${JWT_SECRET:AAABBBBBBBBBBBBBBBBBBCCDDASS}
    expiration: ${JWT_EXPIRATION:3600000}
