server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge_fase3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      read-only: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: America/Sao_Paulo
  graphql:
    http:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/
security:
  jwt:
    secret: ${JWT_SECRET:AAABBBBBBBBBBBBBBBBBBCCDDASS}
    expiration: ${JWT_EXPIRATION:3600000}
